name: Release
on: push

env:
  packageName: "com.nekometer.esnya.inari-udon"

permissions:
  contents: write

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm ci --no-workspaces

      - id: prev_version
        run: |
          prop=$(jq -e -r '.version' "Packages/${{ env.packageName }}/package.json")
          echo "prop=$prop" >> "$GITHUB_OUTPUT"

      - run: npx --no-install semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: version
        run: |
          prop=$(jq -e -r '.version' "Packages/${{ env.packageName }}/package.json")
          echo "prop=$prop" >> "$GITHUB_OUTPUT"
    outputs:
      prev_version: ${{ steps.prev_version.outputs.prop }}
      next_version: ${{ steps.version.outputs.prop }}

  vcc-release:
    runs-on: ubuntu-latest
    needs: semantic-release
    if: needs.semantic-release.outputs.prev_version != needs.semantic-release.outputs.next_version
    steps:
      - uses: actions/checkout@v4
      - run: echo "version=${{ needs.semantic-release.outputs.next_version }}" >> $GITHUB_ENV

      - run: |
          echo "zipFile=${{ env.packageName }}-${{ env.version }}".zip >> $GITHUB_ENV
          echo "unityPackage=${{ env.packageName }}-${{ env.version }}.unitypackage" >> $GITHUB_ENV
      - uses: thedoctor0/zip-release@b57d897cb5d60cb78b51a507f63fa184cfe35554 # 0.7.6
        with:
          type: "zip"
          directory: "Packages/${{env.packageName}}/"
          filename: "../../${{env.zipFile}}" # make the zip file two directories up, since we start two directories in above

      - run: find "Packages/${{env.packageName}}/" -name \*.meta >> metaList
      - uses: pCYSl5EDgo/create-unitypackage@b5c57408698b1fab8b3a84d4b67f767b8b7c0be9 # v1.2.3
        with:
          package-path: ${{ env.unityPackage }}
          include-files: metaList

      - uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # v2
        with:
          tag: v${{ env.version }}
          file: ${{ env.zipFile }}
      - uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # v2
        with:
          tag: v${{ env.version }}
          file: ${{ env.unityPackage }}
      - uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # v2
        with:
          tag: v${{ env.version }}
          file: Packages/${{ env.packageName }}/package.json
